### ISSUE TITLE
Zoom In/Out

### ISSUE THREAD

**Issue by Diktat0ren** [lukasgjetting/Graphr.js#1]
Feature to zoom in and out

**Comment by Diktat0ren** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Zoom in/out](https://trello.com/c/QPQlBf94/7-zoom-in-out)

**Comment by Diktat0ren** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Graf stopper hvis man scroller længere hen af grafen](https://trello.com/c/yp1C1Zyb/9-graf-stopper-hvis-man-scroller-laengere-hen-af-grafen)

**Comment by lukasgjetting** [comment]
Fixed
