### ISSUE TITLE
Graph just cuts off, after scrolling to the side

### ISSUE THREAD

**Issue by Diktat0ren** [lukasgjetting/Graphr.js#3]
O:

**Comment by Diktat0ren** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Graf stopper hvis man scroller længere hen af grafen](https://trello.com/c/yp1C1Zyb/9-graf-stopper-hvis-man-scroller-laengere-hen-af-grafen)

**Comment by lukasgjetting** [comment]
;D
